### ISSUE TITLE
SHMT file size vs. chdb file size

### ISSUE THREAD

**Issue by dyeshurun** [sevenval/SHMT#1]
We started using the extension, seems to be very good.
We did notice that the files created by shmt_create are much bigger then chdb files with the same amount of entries.
For example: 1.9M vs 980K for a map with 25974 entries, where the key is a number (5 digits) and the value is ~15 bytes

What is the impact of this on memory? Can you explain the difference?

Thanks,
Danny

**Comment by alex-schneider** [comment]
Hi @dyeshurun ,

SHMT is internally implemented as "Perfect Hash Function", cmph (which chdb internally uses) as "Minimal Perfect Hash Function".

For both arrays (Hash-Table and Map-Table) SHMT reserves the next 2^p number of slots like the number of entries given. This has the advantage that on every write/resolve operation and every lookup the expensive modulo arithmetic operations omitted. Furthermore, the structure of the Hash-Table in SHMT is designed more complex so on "direct hits" the lookups to the Map-Table ommited. Our tests with over 410,000 entries which we used on the production system (file size: ~42.3M chdb, ~50.8M SHMT) have shown that SHMT is up to 75% faster when writing and up to 35% faster when reading than chdb.

We did not notice any problems with the memory. Both tools internally use the mmap function of the OS which controls and manages the memory.

I hope I could help. Thanks,
Alex

**Comment by dyeshurun** [comment]
Thanks Alex.
I didn't see any problem as well, wanted to know why the differences in file size are.
Anyway, we will test the extension with our data as well. Will let you know the results once done.

Thanks,
Danny

**Comment by filex** [comment]
I close this issue until it becomes a problem. In case, please reopen.

@dyeshurun, if you have any test results to share, we would be happy to hear from you.

**Comment by dyeshurun** [comment]
We have several use cases, one example would be:
10M entries - we were not able to create those in 1 chdb file so we sharded it to 10 files. Sharding is done using the entry key hence files are pretty balanced.

Using chdb each file is ~230M - total of ~2.4G
Using shmt each file is ~350M - total of ~3.6G

Running lookup of 1M entries:
Using chdb - ~24 seconds
Using shmt - ~16 seconds

Pretty good !
Thanks a lot guys.
