### ISSUE TITLE
SHMT::create support Iterable objects as $array

### ISSUE THREAD

**Issue by nowgoo** [sevenval/SHMT#5]
construct a large array in php is memory-consuming, if we can write a Iterable class to read database and use it's instance as an array, life could be much easier. is it possible to do it? thanks.

**Comment by alex-schneider** [comment]
I do not really understand your work-flow. Can you describe your work-flow more precisely? Which kind of array do you use in your code (normal or associative array) for creation of a SHMT?

**Comment by nowgoo** [comment]
Sorry, I'm trying to describe it more precisely. Imaging we have a table like this:

```
CREATE TABLE `ExampleData` (
  `key-field`  varchar(255) NULL ,
  `value-field`  varchar(255) NULL 
);
```

The current way to use SHMT:

```
$data = [];
$db_statement = $db->query("SELECT * FROM ExampleData");
while ($row = $db_statement->fetch()) {
  $data[$row['key-field']] = $row['value-field'];
}
SHMT::create($filename='map.shmt', $data);
```

If the table is big enough, $data could consume a lot of memory. And the **Iterator** way will be like this:

```
class DataIterator implements Iterator {
    private $key = null;
    private $value = null;
    private $stm = null;

    public function __construct($stm) {
        $this->stm = $stm;
    }

    function rewind() {
        $this->next();
    }

    function current() {
        return $this->value;
    }

    function key() {
        return $this->key;
    }

    function next() {
        $row = $this->stm->fetch();
        if ($row) {
            $this->key = $row['key-field'];
            $this->value = $row['value-field'];
        } else {
            $this->key = $this->value = null;
        }
    }

    function valid() {
        return !is_null($this->key);
    }
}

$db_statement = $db->query("SELECT * FROM ExampleData");
$data = new DataIterator($db_statement);
SHMT::create($filename='map.shmt', $data);
```

The advantage of this way is: we didn't construct a large array in PHP, and $data still can be used as an array (support foreach statement). Even more, we can break the SQL query to small queries (to reduce the pressure at MySQL side). 

It's just my thought, if there is something wrong please let me known. Thanks a lot.

**Comment by alex-schneider** [comment]
Sorry, but SHMT intern has no lists of keys or values for any iterations. SHMT calculates the number of bucket by the hash-value of the given key and shows in the bucket for the position in the file where to find the value (if the bucket is not empty).

May be you need APCu or Memcached for you work-flow.

**Comment by nowgoo** [comment]
OK, Thanks very much.

**Comment by alex-schneider** [comment]
Workaround: You can try to work with MySQL limits and to create several *.shmt files. The SHMT has extremely fast initial load for *.shmt files, so you can try to run your lookups in a loop.
