### ISSUE TITLE
undefined symbol: shmt_fetch

### ISSUE THREAD

**Issue by Peter-Sh** [sevenval/SHMT#7]
I've met an error with shmt extension under php 7.1.5

It is building normally (on Debian 9 system) but tests are failing (and in fact extension is not working) because of this error:
``` symbol lookup error: /home/petr/build/php/SHMT/modules/shmt.so: undefined symbol: shmt_fetch```

I am attaching build log and test results.
[shmt_build.txt](https://github.com/sevenval/SHMT/files/1295513/shmt_build.txt)
[php_test_results_20170912_0946.txt](https://github.com/sevenval/SHMT/files/1295516/php_test_results_20170912_0946.txt)

The main differences with your travis config is php version and that I use non-zts debug mode.

It seems that the problem is with inline function shmt_fetch and is somewhat related to compiler mode and/or flags. I've removed inline keyword and the error has been disappeared, and all is working.

**Comment by alex-schneider** [comment]
In the function declaration the keyword `static` seems to be missing. Please try to change the declaration as following:

`static inline shmt_object *shmt_fetch(zend_object *object)`

then to build the extension and to run the tests again.

**Comment by Peter-Sh** [comment]
Thank you, all tests with this patch are passing.

```git diff origin/master
diff --git a/php_shmt.c b/php_shmt.c
index d37df6f..39c3bce 100644
--- a/php_shmt.c
+++ b/php_shmt.c
@@ -10,7 +10,7 @@
 zend_class_entry *ce_shmt;
 zend_object_handlers shmt_handlers;

-inline shmt_object *shmt_fetch(zend_object *object)
+static inline shmt_object *shmt_fetch(zend_object *object)
 {
        return (shmt_object *)((void *)(object) - XtOffsetOf(shmt_object, std));
 }
```

**Comment by alex-schneider** [comment]
Thank you for reporting the bug!
